---
title: "Interim report"
author: "Nitay Alon"
date: "May 15, 2020"
output: html_document
---

Sweden - check after day 70, explore the data some more
France - report separately 
Italy - validate that 52 and 60 makes no difference
Germany - check after 70
Chile - Validate the diff between 60 and 70

```{r load environment libraries}
library(dplyr)
library(tidyverse)
library(plotly)
library(ggplot2)
```


```{r us data}
cutoff <- 12
debug(mainFunction)
usa_data_fine_alpha_grid <- mainFunction('US',60)
plot(usa_data$OBJ)
usa_data_minus_3 <- mainFunction('US',60, 12)
max(usa_data_minus_3$X)
usa_data_minus_3$final_results$single_dim_CI
usa_data$final_results$single_dim_CI
```

```{r plot profile likelihood}
alpha_grid = seq(0.1,0.9,0.01)
hhh_upper_limit = 200
NNN = floor(max(usa_data$X) / 100)
hhh <- 1:hhh_upper_limit
k_grid <- max(usa_data$X) + hhh * NNN
grid_parameters <- expand.grid(alpha_grid,k_grid)
profile_likelihood_data <- data.frame(llk = usa_data$OBJ, alpha = grid_parameters$Var1, K = grid_parameters$Var2)
ggplot(profile_likelihood_data, aes(x = K, y = llk , col = factor(alpha))) +
  geom_line() + 
  ggtitle("Profile likelihood of K")
```


```{r plot US full data set model}
x_mle_upper <- usa_data_minus_3$final_results$one_dim_params[[1]]$x
vw_mle_upper <- usa_data_minus_3$final_results$one_dim_params[[1]]$vw
y_mle_upper <- usa_data_minus_3$final_results$one_dim_params[[1]]$y

x_mle_mid <- usa_data_minus_3$final_results$one_dim_params[[2]]$x
vw_mle_mid <- usa_data_minus_3$final_results$one_dim_params[[2]]$vw
y_mle_mid <- usa_data_minus_3$final_results$one_dim_params[[2]]$y

x_mle_lower <- usa_data_minus_3$final_results$one_dim_params[[3]]$x
vw_mle_lower <- usa_data_minus_3$final_results$one_dim_params[[3]]$vw
y_mle_lower <- usa_data_minus_3$final_results$one_dim_params[[3]]$y

length(usa_data$X) - 12

plot(usa_data$X / 1e5, col = 'blue' , type = 'b', pch=7, panel.first = grid(),
     ylab = "Number of cases * 10^5", xlab = 'Days', xlim = c(0,120), lty = 1, lwd = 2,
     main = sprintf("Predicted (red) vs actual data (blue)"),
     sub = sprintf("%s days removed",cutoff), cex = 0.5)
lines(usa_data$VW / 1e5,col = 'blue', type = 'b', pch=13, lwd = 2, cex = 0.5)
lines(usa_data$Y / 1e5, col = 'blue', type = 'b', pch=19, lwd = 2, cex = 0.5)

lines(x_mle_upper[(1:length(x_mle)) %% 100 == 0] / 1e5, col = 'orange', type = 'b', pch=7, lwd = 1, cex = 0.5)
lines(vw_mle_upper[(1:length(vw_mle)) %% 100 == 0]/ 1e5, col = 'orange', type = 'b', pch=13, lwd = 1, cex = 0.5)
lines(y_mle_upper[(1:length(y_mle)) %% 100 == 0] / 1e5, col = 'orange', type = 'b', pch=19, lwd = 1, cex = 0.5)

lines(x_mle_mid[(1:length(x_mle)) %% 100 == 0] / 1e5, col = 'red', type = 'b', pch=7, lwd = 1, cex = 0.5)
lines(vw_mle_mid[(1:length(vw_mle)) %% 100 == 0]/ 1e5, col = 'red', type = 'b', pch=13, lwd = 1, cex = 0.5)
lines(y_mle_mid[(1:length(y_mle)) %% 100 == 0] / 1e5, col = 'red', type = 'b', pch=19, lwd = 1, cex = 0.5)

lines(x_mle_lower[(1:length(x_mle)) %% 100 == 0] / 1e5, col = 'green', type = 'b', pch=7, lwd = 1, cex = 0.5)
lines(vw_mle_lower[(1:length(vw_mle)) %% 100 == 0]/ 1e5, col = 'green', type = 'b', pch=13, lwd = 1, cex = 0.5)
lines(y_mle_lower[(1:length(y_mle)) %% 100 == 0] / 1e5, col = 'green', type = 'b', pch=19, lwd = 1, cex = 0.5)

legend(0, 14, legend=c("X", "VW",'Y'),pch=c(7,13,19))
abline(v = which.max(y_mle[(1:length(y_mle)) %% 100 == 0]), col = 'black',
       lwd = 1)
abline(v = length(usa_data$X) - 12, col = 'black', lty = 2,
       lwd = 1)
```

1. Plot x,y,wv vs X,Y,VW (for $\hat{K}$)
2. Cut the data the time t1 and the CI for the following days - x,y,vw
3. Find the date where the infected reaches maximum

```{r all conventional data}
Italy_day <- 60
Belgium_day <- 60
USA <- 60
Chile <- 60
Israel <- 64
Germany <- 65
Netherlands_day <- 68
UK <- 70
```

```{r non conventional data}
France <- 65
Sweden <- 65
```
