#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon May 18 08:38:38 2020

@author: nitay
"""

from Python.import_data_set import create_data_frame_for_state
from Python.Grid_search.grid_search_main_method import gridSearch

def main(state_name, starting_day):
    nation_data = create_data_frame_for_state(state_name)
    nation_wide_rtt_results = gridSearch(nation_data,starting_day)
    return(nation_wide_rtt_results)
    
us_grid_search = main('US',60)